Part 1: Theoretical Questionk

1.What are the different data structures used in Tensorflow?. Give some examples?

Answer(1):

TensorFlow, a popular deep learning framework, provides various data structures to work with tensors and datasets. Here are some of the key data structures used in TensorFlow, along with examples:


In [2]:
!pip install tensorflow

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 489.8/489.8 MB 2.7 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.9/22.9 MB 48.4 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.7/440.7 kB 40.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 70.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 15.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.2/130.2 kB 20.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 72.5 MB/s eta 0:00:00:00:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 67.6 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 11.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 65.5 MB/s eta 0:00:00:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 12.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 59.3 MB/s eta

In [7]:
# TensorFlow, a popular deep learning framework, provides various data structures to work with tensors and datasets. Here are some of the key data structures used in TensorFlow, along with examples:

# 1. **Tensor**: Tensors are multi-dimensional arrays that represent the fundamental building blocks of data in TensorFlow. Tensors can be scalars (0-D), vectors (1-D), matrices (2-D), or higher-dimensional arrays.


import tensorflow as tf
scalar = tf.constant(5)        # 0-D tensor (scalar)
vector = tf.constant([1, 2, 3]) # 1-D tensor (vector)
matrix = tf.constant([[1, 2], [3, 4]]) # 2-D tensor (matrix)


print(f"scalar = {scalar}")
print(f"vector = {vector}")
print(f"matrix = {matrix}")


scalar = 5
vector = [1 2 3]
matrix = [[1 2]
 [3 4]]


In [15]:
# 2. **Variable**: Variables are used to store and update trainable parameters (weights and biases) in machine learning models.


import tensorflow as tf
weight = tf.Variable([0.5, 1.0])
print(f"weight = {weight} \n")


# 3. **Placeholder (deprecated)**: Placeholders were used in older versions of TensorFlow for feeding data into a computational graph. However, they have been deprecated in favor of the `tf.data` API and `tf.function`.

# x = tf.compat.v1.placeholder(tf.float32, shape=(None, 3))
# print(f"x = {x}")

# 4.Dataset: The tf.data.Dataset API is used for efficient data input pipelines. It allows you to create, transform, and batch datasets.

data = [[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]]
labels = [0, 1, 0]

dataset = tf.data.Dataset.from_tensor_slices((data, labels))
dataset = dataset.shuffle(buffer_size=100).batch(32)
print(f"dataset = {dataset} \n")


# 5. **SparseTensor**: Sparse tensors are used to represent sparse data efficiently, such as sparse matrices or sparse feature vectors.


# Define the indices as int64
indices = tf.constant([[0, 1], [1, 2]], dtype=tf.int64)
# Define values
values = tf.constant([3.0, 4.0])
# Define the dense_shape with dtype int64
shape = tf.constant([3, 3], dtype=tf.int64)
# Create a SparseTensor
sparse_tensor = tf.SparseTensor(indices, values, shape)

print(f"sparse_tensor = {sparse_tensor} \n")


# 6. **RaggedTensor**: Ragged tensors are used to represent sequences of varying lengths, which are common in natural language processing tasks.


ragged_tensor = tf.ragged.constant([[1, 2], [3, 4, 5], [6]])
print(f"ragged_tensor = {ragged_tensor} \n")

# These are some of the fundamental data structures in TensorFlow. Depending on the specific use case, you may encounter other specialized data structures and abstractions, but these cover the basics for most deep learning tasks. Note that TensorFlow's API evolves over time, so it's essential to refer to the official documentation for the latest information and best practices.

weight = <tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([0.5, 1. ], dtype=float32)> 

dataset = <_BatchDataset element_spec=(TensorSpec(shape=(None, 2), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))> 

sparse_tensor = SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([3. 4.], shape=(2,), dtype=float32), dense_shape=tf.Tensor([3 3], shape=(2,), dtype=int64)) 

ragged_tensor = <tf.RaggedTensor [[1, 2], [3, 4, 5], [6]]> 



2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example?

Answer(2):
In TensorFlow, constants and variables are two different types of tensors used to represent data, but they have distinct characteristics and use cases. Here's how they differ:

1. **TensorFlow Constants**:

   - **Immutable**: Constants are immutable, meaning their values cannot be changed once they are defined. They hold a fixed value throughout the execution of a TensorFlow graph.
   - **Typically for Data**: Constants are often used to represent fixed data values that do not change during training, such as hyperparameters, model configurations, or fixed input data.
   - **Memory Efficiency**: Constants are memory-efficient because they are stored once and shared across the graph.

   Example:

   ```python
   import tensorflow as tf

   # Define a constant tensor
   constant_tensor = tf.constant([1.0, 2.0, 3.0])

   # Attempting to assign a new value to a constant will result in an error
   # constant_tensor.assign([4.0, 5.0, 6.0])  # This will raise an error
   ```

2. **TensorFlow Variables**:

   - **Mutable**: Variables are mutable, allowing their values to be changed during the execution of a TensorFlow graph. They are typically used to store and update the learnable parameters of machine learning models, such as weights and biases.
   - **Training Parameters**: Variables are commonly used for parameters that need to be optimized during training, and they can be updated by optimization algorithms like gradient descent.
   - **Initialization Required**: Variables require an explicit initialization step before they can be used in a session. This initialization sets their initial values.

   Example:

   ```python
   import tensorflow as tf

   # Define a variable tensor
   initial_values = [1.0, 2.0, 3.0]
   variable_tensor = tf.Variable(initial_values)

   # Variables can be updated using assign operations
   variable_tensor.assign([4.0, 5.0, 6.0])

   # Variables need to be explicitly initialized before use in a session
   init = tf.compat.v1.global_variables_initializer()  # Initialization operation
   with tf.compat.v1.Session() as sess:
       sess.run(init)  # Initialize variables
       result = sess.run(variable_tensor)
   ```

In summary, constants are used for fixed, unchanging values in TensorFlow, while variables are used for mutable values that need to be optimized during training. Variables require explicit initialization and can be updated, while constants remain fixed throughout the execution of a TensorFlow graph.

3. Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow.

Answer(3):

These are the basic operations for matrix addition, multiplication, and element-wise operations in TensorFlow as follows.

In [17]:
import tensorflow as tf

# Define two matrices
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])

# Perform matrix addition
addition_result = tf.add(matrix_a, matrix_b)

# Perform matrix multiplication
multiplication_result = tf.matmul(matrix_a, matrix_b)

# Perform element-wise multiplication
element_wise_result = tf.multiply(matrix_a, matrix_b)

print("Matrix Addition:")
print(addition_result.numpy())

print("\nMatrix Multiplication:")
print(multiplication_result.numpy())

print("\nElement-wise Multiplication:")
print(element_wise_result.numpy())


Matrix Addition:
[[ 6  8]
 [10 12]]

Matrix Multiplication:
[[19 22]
 [43 50]]

Element-wise Multiplication:
[[ 5 12]
 [21 32]]


Part 2: Practical Implementation


Task 1: Creating and Manipulating Matrice

1. Create a normal matrix A with dimensions 3x3, using TensorFlow's random_normal function. Display the values of matrix A.

In [19]:
import tensorflow as tf

# Create a 3x3 matrix with random values from a normal distribution
matrix_A = tf.random.normal(shape=(3, 3), mean=0.0, stddev=1.0, dtype=tf.float32)

# Display the values of the matrix
print("Matrix A:")
print(matrix_A.numpy())


Matrix A:
[[-0.48184893 -0.14388245 -0.1955412 ]
 [-0.6539595  -0.53080565  0.45206136]
 [ 0.63473976  0.07630948  1.7150594 ]]


2. Create a Gaussian matrix B with dimensions 4x4, using TensorFlow's truncated_normal function. Display the values of matrix B.

In [20]:
import tensorflow as tf

# Create a 4x4 matrix with random values from a truncated normal distribution
matrix_B = tf.random.truncated_normal(shape=(4, 4), mean=0.0, stddev=1.0, dtype=tf.float32)

# Display the values of the matrix
print("Matrix B:")
print(matrix_B.numpy())


Matrix B:
[[-0.549787    0.6540923  -0.66147316 -0.6913391 ]
 [-0.23713088  0.85479295  1.4096663  -0.08138409]
 [ 1.358484   -0.586029   -0.8784891  -0.4593105 ]
 [ 0.40769148  0.08256792 -0.8812569   0.4299257 ]]


3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 3 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix C.

In [21]:
import tensorflow as tf

# Define the mean and standard deviation
mean = 3.0
stddev = 0.5

# Create a 2x2 matrix with random values from a normal distribution
matrix_C = tf.random.normal(shape=(2, 2), mean=mean, stddev=stddev, dtype=tf.float32)

# Display the values of matrix C
print("Matrix C:")
print(matrix_C.numpy())


Matrix C:
[[2.8154814 2.945449 ]
 [3.766169  3.2527046]]


4. Perform matrix addition between matrix A and matrix B, and store the result in matrix D.

In [22]:
import tensorflow as tf

# Assuming you have matrix A and matrix B as previously defined
matrix_A = tf.random.normal(shape=(3, 3), mean=0.0, stddev=1.0, dtype=tf.float32)
matrix_B = tf.random.truncated_normal(shape=(4, 4), mean=0.0, stddev=1.0, dtype=tf.float32)

# Perform matrix addition between A and B
matrix_D = tf.add(matrix_A, matrix_B)

# Display the result matrix D
print("Matrix D (Result of A + B):")
print(matrix_D.numpy())


InvalidArgumentError: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [3,3] vs. [4,4] [Op:AddV2] name: 

In [23]:
import tensorflow as tf

# Create a 3x3 matrix A with random values
matrix_A = tf.random.normal(shape=(3, 3), mean=0.0, stddev=1.0, dtype=tf.float32)

# Create a 3x3 matrix B with random values
matrix_B = tf.random.normal(shape=(3, 3), mean=0.0, stddev=1.0, dtype=tf.float32)

# Perform matrix addition between A and B
matrix_D = tf.add(matrix_A, matrix_B)

# Display the result matrix D
print("Matrix D (Result of A + B):")
print(matrix_D.numpy())


Matrix D (Result of A + B):
[[-3.7134051  -0.34727752 -0.23913056]
 [ 0.85652435 -0.02615541 -0.62503004]
 [-0.19288328  0.27122486 -1.9390346 ]]


5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.


In [29]:
import tensorflow as tf

# Create a 3x3 matrix A with random values
matrix_A = tf.random.normal(shape=(3, 3), mean=0.0, stddev=1.0, dtype=tf.float32)

# Create a 3x3 matrix B with random values
matrix_B = tf.random.normal(shape=(3, 3), mean=0.0, stddev=1.0, dtype=tf.float32)

# Perform matrix addition between A and B
matrix_D = tf.add(matrix_A, matrix_B)

# Display the result matrix D
print("Matrix D (Result of A + B):")
print(matrix_D.numpy())

# Create matrix C with dimensions 2x3
mean_C = 3.0
stddev_C = 0.5
matrix_C = tf.random.normal(shape=(3, 3), mean=mean_C, stddev=stddev_C, dtype=tf.float32)

# Display the values of matrix C
print("Matrix C:")
print(matrix_C.numpy())

# Perform matrix multiplication between C and D
matrix_E = tf.matmul(matrix_C, matrix_D)

# Display the result matrix E
print("Matrix E (Result of C * D):")
print(matrix_E.numpy())

Matrix D (Result of A + B):
[[-0.63633204  2.106967    0.5883774 ]
 [ 0.5391721  -0.5446354  -1.0650203 ]
 [-0.28847873 -1.4829566  -0.3546988 ]]
Matrix C:
[[3.3812654 3.2255747 3.6240485]
 [3.9899054 2.7906199 2.8738177]
 [3.5540957 3.3152707 2.554994 ]]
Matrix E (Result of C * D):
[[-1.4579285  -0.00685415 -2.7312882 ]
 [-1.8633156   2.6249816  -1.6438364 ]
 [-1.211145    1.8938034  -2.3459344 ]]


Task 2: Performing Additional Matrix Operationk

1. Create a matrix F with dimensions 3x3, initialized with random values using TensorFlow's random_uniform function.

In [30]:
import tensorflow as tf

# Define the shape of the matrix
matrix_shape = (3, 3)

# Create matrix F with random values between 0 and 1
matrix_F = tf.random.uniform(shape=matrix_shape, minval=0, maxval=1, dtype=tf.float32)

# Display the values of matrix F
print("Matrix F:")
print(matrix_F.numpy())


Matrix F:
[[0.35843587 0.74229395 0.65148246]
 [0.31182778 0.24165595 0.69925725]
 [0.88391685 0.5967181  0.40546298]]


2. Calculate the transpose of matrix F and store the result in matrix G

In [32]:
import tensorflow as tf

# Assuming you have matrix F as previously defined
matrix_shape = (3, 3)
matrix_F = tf.random.uniform(shape=matrix_shape, minval=0, maxval=1, dtype=tf.float32)

# Display the values of matrix F
print("Matrix F:")
print(matrix_F.numpy())

# Calculate the transpose of matrix F and store it in matrix G
matrix_G = tf.transpose(matrix_F)

# Display the values of matrix G (the transpose of F)
print("Matrix G (Transpose of F):")
print(matrix_G.numpy())


Matrix F:
[[0.1928389  0.1028955  0.8979058 ]
 [0.7349212  0.3671707  0.5931699 ]
 [0.97469175 0.31764293 0.55295503]]
Matrix G (Transpose of F):
[[0.1928389  0.7349212  0.97469175]
 [0.1028955  0.3671707  0.31764293]
 [0.8979058  0.5931699  0.55295503]]


3. Calculate the element-wise exponential of matrix F and store the result in matrix H.

In [33]:
import tensorflow as tf

# Assuming you have matrix F as previously defined
matrix_shape = (3, 3)
matrix_F = tf.random.uniform(shape=matrix_shape, minval=0, maxval=1, dtype=tf.float32)

# Calculate the element-wise exponential of matrix F and store it in matrix H
matrix_H = tf.math.exp(matrix_F)

# Display the values of matrix H
print("Matrix H (Element-wise Exponential of F):")
print(matrix_H.numpy())


Matrix H (Element-wise Exponential of F):
[[1.804353  1.7801867 1.2760661]
 [1.3365791 1.4984244 1.0284352]
 [2.546889  2.1808167 1.6800363]]


4. Create a matrix I by concatenating matrix F and matrix G horizontally.

In [34]:
import tensorflow as tf

# Assuming you have matrices F and G as previously defined
matrix_shape = (3, 3)
matrix_F = tf.random.uniform(shape=matrix_shape, minval=0, maxval=1, dtype=tf.float32)
# Display the values of matrix F
print("Matrix F:")
print(matrix_F.numpy())
matrix_G = tf.transpose(matrix_F)  # Transpose of F for illustration
# Display the values of matrix F
print("Matrix G (Transpose of F):")
print(matrix_G.numpy())

# Concatenate matrices F and G horizontally to create matrix I
matrix_I = tf.concat([matrix_F, matrix_G], axis=1)

# Display the values of matrix I
print("Matrix I (Concatenation of F and G horizontally):")
print(matrix_I.numpy())


Matrix F:
[[0.41009986 0.72849715 0.5150701 ]
 [0.33113503 0.4869449  0.469409  ]
 [0.41411006 0.13836586 0.6505649 ]]
Matrix G (Transpose of F):
[[0.41009986 0.33113503 0.41411006]
 [0.72849715 0.4869449  0.13836586]
 [0.5150701  0.469409   0.6505649 ]]
Matrix I (Concatenation of F and G horizontally):
[[0.41009986 0.72849715 0.5150701  0.41009986 0.33113503 0.41411006]
 [0.33113503 0.4869449  0.469409   0.72849715 0.4869449  0.13836586]
 [0.41411006 0.13836586 0.6505649  0.5150701  0.469409   0.6505649 ]]


5. Create a matrix J by concatenating matrix F and matrix H vertically.

In [35]:
import tensorflow as tf

# Assuming you have matrices F and G as previously defined
matrix_shape = (3, 3)
matrix_F = tf.random.uniform(shape=matrix_shape, minval=0, maxval=1, dtype=tf.float32)
# Display the values of matrix F
print("Matrix F:")
print(matrix_F.numpy())
matrix_G = tf.transpose(matrix_F)  # Transpose of F for illustration
# Display the values of matrix F
print("Matrix G (Transpose of F):")
print(matrix_G.numpy())

# Concatenate matrices F and G horizontally to create matrix I
matrix_I = tf.concat([matrix_F, matrix_G], axis=0)

# Display the values of matrix I
print("Matrix I (Concatenation of F and G vertically):")
print(matrix_I.numpy())


Matrix F:
[[0.4037652  0.92462206 0.73189807]
 [0.00100589 0.36414814 0.18294764]
 [0.63655496 0.8443724  0.5356635 ]]
Matrix G (Transpose of F):
[[0.4037652  0.00100589 0.63655496]
 [0.92462206 0.36414814 0.8443724 ]
 [0.73189807 0.18294764 0.5356635 ]]
Matrix I (Concatenation of F and G vertically):
[[0.4037652  0.92462206 0.73189807]
 [0.00100589 0.36414814 0.18294764]
 [0.63655496 0.8443724  0.5356635 ]
 [0.4037652  0.00100589 0.63655496]
 [0.92462206 0.36414814 0.8443724 ]
 [0.73189807 0.18294764 0.5356635 ]]
